package com.model;
// Generated Oct 6, 2015 3:47:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bill generated by hbm2java
 */
public class Bill  implements java.io.Serializable {


     private int id;
     private Account account;
     private Customer customer;
     private Date date;
     private Double discount;
     private BigDecimal payment;
     private BigDecimal total;
     private Integer billStatus;
     private Set billdetails = new HashSet(0);

    public Bill() {
    }

	
    public Bill(int id, Account account, Date date) {
        this.id = id;
        this.account = account;
        this.date = date;
    }
    public Bill(int id, Account account, Customer customer, Date date, Double discount, BigDecimal payment, BigDecimal total, Integer billStatus, Set billdetails) {
       this.id = id;
       this.account = account;
       this.customer = customer;
       this.date = date;
       this.discount = discount;
       this.payment = payment;
       this.total = total;
       this.billStatus = billStatus;
       this.billdetails = billdetails;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public BigDecimal getPayment() {
        return this.payment;
    }
    
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Integer getBillStatus() {
        return this.billStatus;
    }
    
    public void setBillStatus(Integer billStatus) {
        this.billStatus = billStatus;
    }
    public Set getBilldetails() {
        return this.billdetails;
    }
    
    public void setBilldetails(Set billdetails) {
        this.billdetails = billdetails;
    }




}


