package com.model;
// Generated Oct 6, 2015 3:47:11 PM by Hibernate Tools 4.3.1



/**
 * BilldetailId generated by hbm2java
 */
public class BilldetailId  implements java.io.Serializable {


     private int billId;
     private int productId;

    public BilldetailId() {
    }

    public BilldetailId(int billId, int productId) {
       this.billId = billId;
       this.productId = productId;
    }
   
    public int getBillId() {
        return this.billId;
    }
    
    public void setBillId(int billId) {
        this.billId = billId;
    }
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BilldetailId) ) return false;
		 BilldetailId castOther = ( BilldetailId ) other; 
         
		 return (this.getBillId()==castOther.getBillId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBillId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


