package com.model;
// Generated Oct 6, 2015 3:47:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Billdetail generated by hbm2java
 */
public class Billdetail  implements java.io.Serializable {


     private BilldetailId id;
     private Bill bill;
     private Product product;
     private int quantity;
     private BigDecimal price;

    public Billdetail() {
    }

    public Billdetail(BilldetailId id, Bill bill, Product product, int quantity, BigDecimal price) {
       this.id = id;
       this.bill = bill;
       this.product = product;
       this.quantity = quantity;
       this.price = price;
    }
   
    public BilldetailId getId() {
        return this.id;
    }
    
    public void setId(BilldetailId id) {
        this.id = id;
    }
    public Bill getBill() {
        return this.bill;
    }
    
    public void setBill(Bill bill) {
        this.bill = bill;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


