package com.model;
// Generated Oct 6, 2015 3:47:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Orderdetail generated by hbm2java
 */
public class Orderdetail  implements java.io.Serializable {


     private OrderdetailId id;
     private Order order;
     private Product product;
     private BigDecimal orderPrice;
     private int orderQuantity;

    public Orderdetail() {
    }

    public Orderdetail(OrderdetailId id, Order order, Product product, BigDecimal orderPrice, int orderQuantity) {
       this.id = id;
       this.order = order;
       this.product = product;
       this.orderPrice = orderPrice;
       this.orderQuantity = orderQuantity;
    }
   
    public OrderdetailId getId() {
        return this.id;
    }
    
    public void setId(OrderdetailId id) {
        this.id = id;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public BigDecimal getOrderPrice() {
        return this.orderPrice;
    }
    
    public void setOrderPrice(BigDecimal orderPrice) {
        this.orderPrice = orderPrice;
    }
    public int getOrderQuantity() {
        return this.orderQuantity;
    }
    
    public void setOrderQuantity(int orderQuantity) {
        this.orderQuantity = orderQuantity;
    }




}


