package com.model;
// Generated Oct 6, 2015 3:47:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private int id;
     private Account account;
     private Supply supply;
     private Date date;
     private Set orderdetails = new HashSet(0);

    public Order() {
    }

	
    public Order(int id, Account account, Supply supply, Date date) {
        this.id = id;
        this.account = account;
        this.supply = supply;
        this.date = date;
    }
    public Order(int id, Account account, Supply supply, Date date, Set orderdetails) {
       this.id = id;
       this.account = account;
       this.supply = supply;
       this.date = date;
       this.orderdetails = orderdetails;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Supply getSupply() {
        return this.supply;
    }
    
    public void setSupply(Supply supply) {
        this.supply = supply;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getOrderdetails() {
        return this.orderdetails;
    }
    
    public void setOrderdetails(Set orderdetails) {
        this.orderdetails = orderdetails;
    }




}


