package com.model;
// Generated Oct 6, 2015 3:47:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int id;
     private Categories categories;
     private String productName;
     private String productInfo;
     private int valueQuantity;
     private Set billdetails = new HashSet(0);
     private Set orderdetails = new HashSet(0);

    public Product() {
    }

	
    public Product(int id, Categories categories, String productName, int valueQuantity) {
        this.id = id;
        this.categories = categories;
        this.productName = productName;
        this.valueQuantity = valueQuantity;
    }
    public Product(int id, Categories categories, String productName, String productInfo, int valueQuantity, Set billdetails, Set orderdetails) {
       this.id = id;
       this.categories = categories;
       this.productName = productName;
       this.productInfo = productInfo;
       this.valueQuantity = valueQuantity;
       this.billdetails = billdetails;
       this.orderdetails = orderdetails;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getProductInfo() {
        return this.productInfo;
    }
    
    public void setProductInfo(String productInfo) {
        this.productInfo = productInfo;
    }
    public int getValueQuantity() {
        return this.valueQuantity;
    }
    
    public void setValueQuantity(int valueQuantity) {
        this.valueQuantity = valueQuantity;
    }
    public Set getBilldetails() {
        return this.billdetails;
    }
    
    public void setBilldetails(Set billdetails) {
        this.billdetails = billdetails;
    }
    public Set getOrderdetails() {
        return this.orderdetails;
    }
    
    public void setOrderdetails(Set orderdetails) {
        this.orderdetails = orderdetails;
    }




}


