package com.model;
// Generated Oct 6, 2015 3:47:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private int id;
     private String role;
     private String permisson;
     private Set accounts = new HashSet(0);

    public Roles() {
    }

	
    public Roles(int id, String role) {
        this.id = id;
        this.role = role;
    }
    public Roles(int id, String role, String permisson, Set accounts) {
       this.id = id;
       this.role = role;
       this.permisson = permisson;
       this.accounts = accounts;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getPermisson() {
        return this.permisson;
    }
    
    public void setPermisson(String permisson) {
        this.permisson = permisson;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }




}


