package com.model;
// Generated Oct 6, 2015 3:47:11 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Supply generated by hbm2java
 */
public class Supply  implements java.io.Serializable {


     private int id;
     private Serializable supplyName;
     private Serializable address;
     private String phone;
     private String email;
     private Set orders = new HashSet(0);

    public Supply() {
    }

	
    public Supply(int id, Serializable supplyName, Serializable address, String phone) {
        this.id = id;
        this.supplyName = supplyName;
        this.address = address;
        this.phone = phone;
    }
    public Supply(int id, Serializable supplyName, Serializable address, String phone, String email, Set orders) {
       this.id = id;
       this.supplyName = supplyName;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.orders = orders;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Serializable getSupplyName() {
        return this.supplyName;
    }
    
    public void setSupplyName(Serializable supplyName) {
        this.supplyName = supplyName;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


